name: Deploy Domain-management-engine

on:
  push:
    branches: [main]
    paths:
      - 'backend/services/domain-management-engine/**'
      - 'backend/shared/**'
  workflow_dispatch:

env:
  PROJECT_ID: nucleus-master
  REGION: me-west1
  SERVICE_NAME: domain-management-engine
  REPOSITORY: nucleus-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      - run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      - run: |
          docker build -t me-west1-docker.pkg.dev/nucleus-master/nucleus-repo/domain-management-engine:${{ github.sha }} -f backend/services/domain-management-engine/Dockerfile ./Dockerfile .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      - run: |
          gcloud run deploy ${{ env.SERVICE_NAME }}             --image me-west1-docker.pkg.dev/nucleus-master/nucleus-repo/domain-management-engine:${{ github.sha }}"             --memory 512Mi --cpu 1 --min-instances 0 --max-instances 10
